die unless defaults file exists

diff --git a/common/etc/init.d/metamod-catalyst b/common/etc/init.d/metamod-catalyst
--- a/common/etc/init.d/metamod-catalyst
+++ b/common/etc/init.d/metamod-catalyst
@@ -41,6 +41,9 @@ GROUP=
 if [ -f "/etc/default/catalyst-$APPID" ]; then
     # use this file to set prefork engine + master_config path
     . "/etc/default/catalyst-$APPID"
+else
+    echo "Missing defaults file /etc/default/catalyst-$APPID"
+    exit 1
 fi
 
 # -------------
